---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: devopsapp
  namespace: web-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: swiggy
  template:
    metadata:
      labels:
        app: swiggy
    spec:
      containers:
        - name: cont-1
          image: nihanth19/webapps:apps
          ports:
            - containerPort: 8080
      imagePullSecrets:
        - name: flm




---
apiVersion: v1
kind: Service
metadata:
  name: appsvc
  namespace: web-app
spec:
  type: LoadBalancer
  selector:
    app: swiggy
  ports:
    - port: 8080
      targetPort: 8080
